force-app/main/default/objects/Date_Shift_Object__c/Date_Shift_Object__c.object-meta.xml
<CustomObject>
    <label>Date Shift Object</label>
    <nameField>
        <displayFormat>DSO-{00}</displayFormat>
        <label>Date Shift Object ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Date Shift Objects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Date_Shift_Object__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Checked if this item should be included in the list of tasks.</description>
    <inlineHelpText>Checked if this item should be included in the list of tasks.</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Date_Shift_Object__c/fields/Adjust_Minutes__c.field-meta.xml
<CustomField>
    <fullName>Adjust_Minutes__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checked to shift dates and times in the record by minutes, unchecked to adjust by whole days instead (e.g., tasks due and calendar events should shift by whole days).</description>
    <inlineHelpText>Checked to shift dates and times in the record by minutes, unchecked to adjust by whole days instead (e.g., tasks due and calendar events should shift by whole days).</inlineHelpText>
    <label>Adjust Minutes</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Date_Shift_Object__c/fields/Object_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Object_API_Name__c</fullName>
    <description>API Name of the object whose Date and DateTime fields are to be shifted.</description>
    <inlineHelpText>API Name of the object whose Date and DateTime fields are to be shifted.</inlineHelpText>
    <label>Object API Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Date_Shift_Object__c/fields/Weekdays_Only__c.field-meta.xml
<CustomField>
    <fullName>Weekdays_Only__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checked if the shifted dates should be further shifted to fall only on weekdays.</description>
    <inlineHelpText>Checked if the shifted dates should be further shifted to fall only on weekdays.</inlineHelpText>
    <label>Weekdays Only</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/DemoDateShifterTest.cls
//  Test class and metbods for the DemoDateShifter Lightning component.
//
//  This code is provided AS IS, with no warranty or guarantee of suitability for use.
//  Contact: john.meyer@salesforce.com

@isTest
private without sharing class DemoDateShifterTest {

    private static final Integer DAYS = 7;
    private static final Integer MINUTES = DAYS * 24 * 60;
    private static Date today = Date.today();
    private static Date nextWeek = today.addDays(DAYS);
    private static DateTime now = DateTime.now();
    private static DateTime nextWeekTime = now.addMinutes(MINUTES);


    @testSetup
    static void setup () {

        List<Shipment> shipments = new List<Shipment>();
        for (Integer i = 0; i < 7; i++)
            shipments.add(new Shipment (
                ShipToName = 'Test Name',
                ActualDeliveryDate = now.addDays(i)
            ));
        insert shipments;

        List<Task> tasks = new List<Task>();
        for (Integer i = 0; i < 7; i++)
            tasks.add(new Task (
                OwnerId = UserInfo.getUserId(),
                Status = 'Not Started',
                Subject = 'Test',
                Priority = 'Normal',
                ActivityDate = today.addDays(i)
            ));
        insert tasks;        

        insert new Date_Shift_Object__c(
            Object_API_Name__c = 'Shipment',
            Active__c = true,
            Adjust_Minutes__c = true,
            Weekdays_Only__c = false
        );
        insert new Date_Shift_Object__c(
            Object_API_Name__c = 'Task',
            Active__c = true,
            Adjust_Minutes__c = false,
            Weekdays_Only__c = true
        );
    }

    @isTest
    static void testGetOrgObjectList () {

        Test.startTest();

        List<DemoDateShifter.Selector> selectors = DemoDateShifter.getOrgObjectList();
        Boolean found = false;
        for (DemoDateShifter.Selector selector : selectors)
            if (selector.apiName == 'Task') {
                found = true;
                break;
            }
        System.assert(found);

        Test.stopTest();
    }

    @isTest
    static void testCustomDateShifterSettings () {

        Test.startTest();

        DemoDateShifter.DateShifterSettings setting = DemoDateShifter.getCustomDateShifterSettings();
        System.assert(!setting.settingsFound);

        DemoDateShifter.setCustomDateShifterSettings ('Shipment', 'ActualDeliveryDate');
        setting = DemoDateShifter.getCustomDateShifterSettings();
        System.assert(setting.settingsFound);

        DemoDateShifter.deleteCustomDateShifterSettings ();
        setting = DemoDateShifter.getCustomDateShifterSettings();
        System.assert(!setting.settingsFound);

        Test.stopTest();
    }

    @isTest
    static void testGetDateTimeFields () {

        Test.startTest();

        List<DemoDateShifter.Selector> selectors = DemoDateShifter.getDateTimeFields('Shipment');
        Boolean found = false;
        for (DemoDateShifter.Selector selector : selectors)
            if (selector.apiName == 'ActualDeliveryDate') {
                found = true;
                break;
            }
        System.assert(found);

        Test.stopTest();
    }

    @isTest
    static void testGetMinutesToShift () {

        Test.startTest();

        DemoDateShifter.DateDifference diff;
        diff = DemoDateShifter.getMinutesToShift(now.format('yyyy-MM-dd\'T\'HH:mm:ss.SSS\'Z\'','GMT'),
            'Shipment', 'ExpectedDeliveryDate');
        System.assert(!diff.validQuery);
        diff = DemoDateShifter.getMinutesToShift(now.format('yyyy-MM-dd\'T\'HH:mm:ss.SSS\'Z\'','GMT'),
            'Shipment', 'ActualDeliveryDate');
        System.assert(diff.validQuery);

        Test.stopTest();
    }

    @isTest
    static void testDateShift () {

        Test.startTest();

        DemoDateShifter.dateShift(MINUTES, DAYS);
        // Task tsk = [SELECT ActivityDate FROM Task ORDER BY ActivityDate ASC LIMIT 1];
        // Shipment ship = [SELECT ActualDeliveryDate FROM Shipment ORDER BY ActualDeliveryDate ASC LIMIT 1];

        //System.assert(tsk.ActivityDate.isSameDay(nextWeek));
        //System.assert(Math.abs(ship.ActualDeliveryDate.getTime() - nextWeekTime.getTime()) < 10000);

        Test.stopTest();
    }

}